modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="mctoolkit_fusion"
version="1.0.0"
displayName="MCtoolkit Fusion"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Guadalupe, MCreator"

[[dependencies.mctoolkit_fusion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




